### PR TITLE
remove unused scripts

### PR DESCRIPTION
**Pull request by Madhu-1**
**Describe what this PR does**
This PR removes unused test scripts, updates the gometalinter version to `2.0.12`

### CODE REVIEW

**Comment by Madhu-1** [comment]
@humblec CI is passing PTAL

**Comment by humblec** [comment]
@JohnStrunk Can you please review this PR ?

**Comment by Madhu-1** [comment]
@JohnStrunk gometlinter upgraded from "2.0.11" to "2.0.12" in this PR.

**Comment by Madhu-1** [comment]
@JohnStrunk yes you are correct, My bad :( in have updated the lint version in wrong fine

made required changes PTAL

**Pull request merged**
