### PR TITLE
Update driver version & changelog to 0.0.9

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**Describe what this PR does**
Provide some context for the reviewer

**Is there anything that requires special attention?**
Do you have any questions? Did you do something clever?

**Related issues:**
Mention any github issues relevant to this PR

### CODE REVIEW

**Comment by Madhu-1** [comment]
retest this please

**Comment by Madhu-1** [comment]
@humblec CI is failing

**Comment by humblec** [comment]
@nigelbabu Can you please take a look at failure in CI. I dont see any thing which can be done from PR pov.

**Comment by Madhu-1** [comment]
Logs from CI
```
05:41:52  > git checkout -f db6c5c5a7071b37cad11e6c154ee837b3228a27a
05:41:52 Commit message: "Add a travis.yml and a test (#27)"
05:41:52  > git rev-list --no-walk b617193badedcd821a36933657ae0fdcb6bcdce8 # timeout=10
05:41:52 [gluster_csi-driver-smoke] $ /bin/sh -xe /tmp/jenkins6307772861721071570.sh
05:41:52 + set +x
05:41:56 [gluster_csi-driver-smoke] $ /bin/sh -xe /tmp/jenkins7206022410969334955.sh
05:41:56 + scripts/common/bootstrap.sh /home/gluster/workspace/gluster_csi-driver-smoke/scripts/csi-driver-smoke/run-test.sh ghprbPullId=88
05:41:56 /tmp/jenkins7206022410969334955.sh: line 2: scripts/common/bootstrap.sh: No such file or directory
05:41:56 Build step 'Execute shell' marked build as failure
05:41:56 Performing Post build task...
05:41:56 Match found for :Building remotely : True
05:41:56 Logical operation result is TRUE
05:41:56 Running script  : # cico-node-done-from-ansible.sh
05:41:56 # A script that releases nodes from a SSID file written by
05:41:56 SSID_FILE=${SSID_FILE:-$WORKSPACE/cico-ssid}
05:41:56 
05:41:56 for ssid in $(cat ${SSID_FILE})
05:41:56 do
05:41:56     cico -q node done $ssid
05:41:56 done
05:41:56 
05:41:56 [gluster_csi-driver-smoke] $ /bin/sh -xe /tmp/jenkins666664691614051449.sh
05:41:56 + SSID_FILE=/home/gluster/workspace/gluster_csi-driver-smoke/cico-ssid
05:41:56 ++ cat /home/gluster/workspace/gluster_csi-driver-smoke/cico-ssid
05:41:56 + for ssid in '$(cat ${SSID_FILE})'
05:41:56 + cico -q node done 8d3d761f
```

**Comment by nigelbabu** [comment]
retest this please

**Comment by Madhu-1** [comment]
retest this please

**Comment by Madhu-1** [comment]
retest this please

**Comment by humblec** [comment]
retest this please

**Comment by Madhu-1** [comment]
retest this please

**Comment by Madhu-1** [comment]
@humblec can you rebase this patch?

**Pull request merged**
