### PR TITLE
updated readme file

### PR DESCRIPTION
**Pull request by Madhu-1**
now readme contains the steps to build
docker container and updated the deployment changes in readme.

Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1 can you update the (sample) outputs from the system once deployment is done ?

**Comment by Madhu-1** [comment]
sure i will update it

**Comment by Madhu-1** [comment]
@humblec updated readme file PTAL

**Comment by humblec** [comment]
@Madhu-1 do we need to fill the `gd2 cluster` deployment ? if you have it its also nice to have.

**Comment by Madhu-1** [comment]
@humblec, current gd2 deployment is not complete yet, it uses the embedded ETCD which is not supported,

am working on deploying an external ETCD and use that configuration to start glusterd2 container, once it's done I will update gd2 yaml file and the output from it

**Pull request merged**
