### PR TITLE
update dockerfile to use nightly gluster release6 repo

### PR DESCRIPTION
**Pull request by Madhu-1**
**Describe what this PR does**
update dockerfile to use the nightly gluster release6 repo

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
https://github.com/gluster/glusterd2/pull/1504

**Comment by nixpanic** [comment]
What is the reason for this? Just because "glusterd2 does it" is not a very good explanation :)

**Comment by Madhu-1** [comment]
@nixpanic glusterd2 and gluster-csi works together.  if glusterd2 uses release6 bits and if we use master bits we may face compatibility issues, keeping both the dependency to same will solve this issue.

**Comment by Madhu-1** [comment]
https://github.com/gluster/gluster-csi-driver/pull/124

**Comment by kshlm** [comment]
Maybe we should move all the GCS container build files into the GCS repo itself. That makes it easier to keep the images inline with each other.

**Pull request merged**
