### PR TITLE
update vendor to point to k8s stable release

### PR DESCRIPTION
**Pull request by Madhu-1**
**Describe what this PR does**
updated Gopkg.toml file and lock file to point to kubernetes latest stable release (1.12.0)

Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1 tests are failing.

**Comment by Madhu-1** [comment]
@humblec tests are failing not because of this PR
```
Step 3/4 : RUN yum -y install glusterfs-fuse && yum clean all -y
 ---> Running in 9dcf9e2b84b6
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:
     1. Contact the upstream for the repository and get them to fix the problem.
     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).
     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...
     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:
            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>
     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:
            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
Cannot find a valid baseurl for repo: base/7/x86_64
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
12: Timeout on http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
The command '/bin/sh -c yum -y install glusterfs-fuse && yum clean all -y' returned a non-zero code: 1
```

**Comment by humblec** [comment]
ok to test

**Comment by humblec** [comment]
@Madhu-1 thanks. That looks a temporary failure. Retriggering the tests

**Comment by Madhu-1** [comment]
locally build is passing for me
```
Go1.9 or later is available on the system.

dep package is available
gometalinter package is available

Installing vendored packages

Building glusterfs csi driver
go build -o build/glusterfs-csi-driver  cmd/glusterfs/main.go

```

**Comment by Madhu-1** [comment]
Logs from centos CI
```
08:59:41 go build -o build/glusterfs-csi-driver  cmd/glusterfs/main.go
08:59:44 # github.com/gluster/gluster-csi-driver/vendor/k8s.io/client-go/transport
08:59:44 vendor/k8s.io/client-go/transport/round_trippers.go:437:9: undefined: strings.Builder
```

yes Centos CI will fail as it uses `golang 1.9.4`  `strings.Builder` was added in Go 1.10 
if we want to upgrade to kubernetes latest version, we need a support for Go 1.10 and higher

**Comment by Madhu-1** [comment]
@JohnStrunk 
gometalinter is not excluding the vendor directory in `travis` 
```
/home/travis/gopath/src/github.com/gluster/gluster-csi-driver/vendor/golang.org/x/net/http2/go111.go:16:27: invalid operation: trace (variable of type *clientTrace) has no field or method WroteHeaderField
/home/travis/gopath/src/github.com/gluster/gluster-csi-driver/vendor/golang.org/x/net/http2/go111.go:17:9: invalid operation: trace (variable of type *clientTrace) has no field or method WroteHeaderField
/home/travis/gopath/src/github.com/gluster/gluster-csi-driver/vendor/golang.org/x/net/http2/go111.go:12:31: invalid operation: trace (variable of type *clientTrace) has no field or method WroteHeaderField
2018/10/15 05:01:16 couldn't load packages due to errors: github.com/gluster/gluster-csi-driver/vendor/golang.org/x/net/http2
DEBUG: [Oct 15 05:01:16.540] [unconvert.1]: unconvert linter took 13.613507076s
DEBUG: [Oct 15 05:01:16.547] [ineffassign.2]: ineffassign linter took 6.513064ms
couldn't load packages due to errors: github.com/gluster/gluster-csi-driver/vendor/golang.org/x/net/http2
DEBUG: [Oct 15 05:01:32.980] [megacheck.3]: megacheck linter took 16.433488236s
DEBUG: [Oct 15 05:01:46.716] [gosec.4]: gosec linter took 13.734458349s
DEBUG: [Oct 15 05:01:46.721] [gocyclo.5]: gocyclo linter took 5.458592ms
/home/travis/gopath/src/github.com/gluster/gluster-csi-driver/vendor/golang.org/x/net/http2/go111.go:16:27: invalid operation: trace (variable of type *clientTrace) has no field or method WroteHeaderField
/home/travis/gopath/src/github.com/gluster/gluster-csi-driver/vendor/golang.org/x/net/http2/go111.go:17:9: invalid operation: trace (variable of type *clientTrace) has no field or method WroteHeaderField
/home/travis/gopath/src/github.com/gluster/gluster-csi-driver/vendor/golang.org/x/net/http2/go111.go:12:31: invalid operation: trace (variable of type *clientTrace) has no field or method WroteHeaderField
2018/10/15 05:02:02 could not type check: couldn't load packages due to errors: github.com/gluster/gluster-csi-driver/vendor/golang.org/x/net/http2
```

**Comment by humblec** [comment]
@Madhu-1 can you disable vendor with --exclude vendor and see it helps  as discussed here @ https://github.com/alecthomas/gometalinter/issues/143#issuecomment-230848811
If yes, we will replace `--vendor` with `--exclude..`

**Comment by Madhu-1** [comment]
@humblec `--exclude=vendor` didn't work

**Comment by JohnStrunk** [comment]
> @JohnStrunk
> gometalinter is not excluding the vendor directory in `travis`

The errors are coming from the vendor directory, but I believe the issue is a bit different. Travis passes for golang 1.11.x and stable, but it fails for the 1.10.x build. It looks like there are library versions being pulled into the 1.10 build that aren't compatible (`go111.go`). The linter tools don't run directly against the vendor directory, but they do need to read those files in order to lint our source. What appears to be happening is that it's failing to be able to make sense of those libraries, so it looks like it's linting vendor.

Why the compile succeeds, but linting fails :man_shrugging:

**Comment by Madhu-1** [comment]
Any suggestions are welcome to support build against golang `1.10.x`.  As of now I will be sticking to build against golang `1.11.1` and `stable` version

**Comment by JohnStrunk** [comment]
According to https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#go 1.10.2 should be sufficient. I think we've got a problem someplace in `Gopkg.toml` that predates this PR.

**Comment by humblec** [comment]
@JohnStrunk @Madhu-1 couple of thoughts here:  ideally we should have an option for `linter` to exclude `vendor`, failing linter on vendor is not something we have to worry. Secondly, if linter passes we should be able to support `1.10.x` as well, isnt it ?

**Comment by Madhu-1** [comment]
@humblec yes we have an option to exclude `vendor` from `linter` ie ```--vendor```
yes if linter passes we can support `1.10.x` 
I have some more test to do on this one. i will update this PR if it works

**Comment by Madhu-1** [comment]
Yay!! CI is passed @humblec @JohnStrunk PTAL

**Comment by Madhu-1** [comment]
@humblec PTAL

**Comment by humblec** [comment]
> Yay!! CI is passed @humblec @JohnStrunk PTAL

AWESOME!!  Thanks .. LGTM.

**Pull request merged**
