### PR TITLE
support for CSI v1.0.0

### PR DESCRIPTION
**Pull request by Madhu-1**
Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

**Describe what this PR does**
This patch updates the `gluster-csi-driver` for CSI v1.0.0

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1 may be its good to wait  for `1.13` then move to `1.0.0`

**Comment by Madhu-1** [comment]
@humblec yes waiting for kubernetes `1.13` release added `do-not-merge` label.

**Comment by humblec** [comment]
we will cut CSI version `1.0.0` with this in :)

**Comment by humblec** [comment]
LGTM. I am planning to merge this PR to bring in cloning support in our driver.  The csi driver in docker hub will only be updated once the GCS deployment will have 1.13 support, even alpha or beta version is good for us.

**Pull request merged**
