### PR TITLE
Add clone functionality.

### PR DESCRIPTION
**Pull request by humblec**
This patch add support for cloning functionality
in glusterfs CSI driver when volumesource is filled
in the request.

Fix: https://github.com/gluster/gluster-csi-driver/issues/100

Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**Describe what this PR does**
Provide some context for the reviewer

**Is there anything that requires special attention?**
Do you have any questions? Did you do something clever?

**Related issues:**
Mention any github issues relevant to this PR

### CODE REVIEW

**Comment by humblec** [comment]
The CSI test is missing this capability and causing this build to fail. I have sent a PR to resolve this issue. https://github.com/kubernetes-csi/csi-test/pull/145

**Comment by humblec** [comment]
@Madhu-1 The above mentioned PR is merged!..

**Comment by Madhu-1** [comment]
retest this please

**Comment by humblec** [comment]
@Madhu-1 Agreed.. Lets wait some more.

**Pull request closed without merging**
