### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jayunit100**
Minor note about the docker version, since alot of folks run kube on < 17.05

### CODE REVIEW

**Comment by Madhu-1** [comment]
ok to test

**Comment by Madhu-1** [comment]
@jayunit100 CI is failing, can you fix it?

**Comment by JohnStrunk** [comment]
@jayunit100 The problem is line length >80:

```
$ scripts/lint-text.sh --require-all
mdl --style scripts/mdl-style.rb ./README.md 
./README.md:35: MD013 Line length
A detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
```

We're currently having other CI problems due to a change in gometalinter, so don't worry about failures other than above.

**Comment by humblec** [comment]
@jayunit100 thanks ! Can you take a look at this error and update the PR ?

**Pull request closed without merging**
